"""First-pass assistant coding of general ideas, separate from heading categories.

Each item is (normalized idea, 1-based supporting segment numbers). Complete saved
answers were also read for context/equations. This is not blinded or expert coding.
Pure notation/unit definitions, historical dates, specific illustrative cases,
follow-up offers and paraphrased repeats do not add general ideas.
"""
CODES = {
("coulomb's law", 'English'): [
('Coulomb law describes electric force between charges.', [1]),
('Increasing either charge increases the force.', [7,8]),
('Force decreases with the square of separation.', [10]),
('Like charges repel.', [15]),
('Opposite charges attract.', [16]),
],
("coulomb's law", 'Hindi'): [
('Coulomb law describes electrostatic force between point charges.', [1,2]),
('Force is proportional to the product of charges.', [10]),
('Force is inversely proportional to squared separation.', [11]),
('Like charges repel.', [7]),
('Opposite charges attract.', [8]),
],
('crystal field theory', 'English'): [
('Ligand electric fields split metal d-orbital energies.', [1,2]),
('An isolated metal ion has five degenerate d orbitals.', [3]),
('Ligands contain electron pairs.', [4]),
('Ligand electrons repel metal d electrons.', [5]),
('Different d orbitals have different orientations relative to ligands.', [6]),
('Greater orbital repulsion produces a higher orbital energy.', [7]),
('Octahedral coordination involves six ligands.', [9]),
('Octahedral ligands approach along the coordinate axes.', [10]),
('The axial dz2 and dx2-y2 orbitals point toward ligands and form the higher-energy eg group.', [11,12]),
('The other three orbitals point between ligands and form the lower-energy t2g group.', [13]),
('Crystal-field splitting energy governs orbital occupancy.', [16]),
('Small splitting favors higher-orbital occupancy and high spin rather than pairing.', [17,18]),
('Large splitting favors pairing in lower orbitals and low spin.', [19,20]),
('Strong-field ligands produce larger splitting than weak-field ligands.', [24]),
('Tetrahedral coordination involves four ligands.', [25]),
('Tetrahedral orbital splitting has the reverse ordering of octahedral splitting.', [26]),
('Tetrahedral splitting is smaller than octahedral splitting.', [27]),
('Small tetrahedral splitting usually leads to high-spin complexes.', [28]),
('Absorption for transitions between split d levels explains color.', [30]),
('Unpaired-electron number determines paramagnetism.', [31]),
('Spin depends on the competition between splitting and pairing energy.', [32]),
('The d-electron arrangement contributes crystal-field stabilization.', [33]),
('Coordination geometry affects orbital splitting patterns.', [34]),
('CFT treats metal-ligand interactions as purely electrostatic.', [37]),
('CFT inadequately describes covalent metal-ligand bonding.', [38]),
('Ligand-field or molecular-orbital theory gives a more complete bonding description.', [38]),
],
('crystal field theory', 'Hindi'): [
('CFT is used to explain coordination-compound structure, color, magnetism and stability.', [1]),
('Ligands are modeled as negative charges or electric dipoles.', [2]),
('Ligand electric fields split metal d-orbital energies.', [3,5,6]),
('An isolated metal ion has five degenerate d orbitals.', [4]),
('Octahedral coordination involves six ligands.', [7]),
('The axial dz2 and dx2-y2 orbitals form the higher-energy eg group.', [8]),
('The dxy, dxz and dyz orbitals form the lower-energy t2g group.', [9]),
('The octahedral groups shift by minus 0.4 and plus 0.6 of the splitting energy.', [11]),
('Tetrahedral coordination involves four ligands.', [12]),
('Tetrahedral splitting reverses the octahedral ordering: t2 is above e.', [13,14,15]),
('Tetrahedral complexes commonly have high-spin configurations.', [17]),
('Spin depends on the competition between splitting and pairing energy.', [18,19,20]),
('Smaller splitting than pairing energy favors separate orbital occupancy and high spin.', [21]),
('Larger splitting than pairing energy favors electron pairing and low spin.', [22]),
('Absorbed light can promote electrons between split d levels.', [26]),
('Selective visible-light absorption gives complexes their color.', [27,28]),
('Unpaired electrons produce paramagnetism.', [30]),
('Complete electron pairing produces diamagnetism.', [31]),
('CFT treats metal-ligand interactions as electrostatic.', [34]),
('CFT inadequately describes covalent bonding character.', [34]),
('Ligand-field or molecular-orbital theory gives a more complete description.', [35]),
],
('electrostatic shielding', 'English'): [
('A closed conducting enclosure shields its interior from external electric fields.', [1,21]),
('Conductors contain mobile free electrons.', [2]),
('An applied field moves the free electrons.', [3,4]),
('Redistributed electrons accumulate at the conductor surface.', [5]),
('Charge redistribution creates an induced electric field.', [6]),
('The induced field opposes the applied field.', [7]),
('Field cancellation makes the internal field zero at electrostatic equilibrium.', [8,9,19]),
('A Faraday cage is a conducting enclosure demonstrating shielding.', [10]),
('Shielding does not mean that electric charge cannot enter the conductor.', [18]),
],
('electrostatic shielding', 'Hindi'): [
('A conducting enclosure shields its interior from an external electrostatic field.', [1,5,10]),
('An external electric field redistributes the conductor free electrons.', [2]),
('Redistribution produces induced surface charges.', [3]),
('The resulting internal electric field is zero at electrostatic equilibrium.', [3,4]),
('A shielding metal mesh or enclosure is called a Faraday cage.', [7,8]),
],
('lorentz force', 'English'): [
('Lorentz force combines electric and magnetic forces on a charge.', [1,8,10]),
('Electric force acts whether the charged particle moves or is stationary.', [9]),
('Magnetic force requires motion and is zero for a stationary charge.', [11,14]),
('Magnetic force is zero when velocity is parallel to the field.', [15]),
('Magnetic force is maximal for velocity perpendicular to the field.', [16]),
('Positive-charge magnetic-force direction follows the velocity-cross-field right-hand rule.', [17,18]),
('Negative charge reverses that force direction.', [19]),
('Electric fields can increase or decrease a charged particle speed.', [23]),
('A magnetic field alone changes motion direction without changing speed.', [23]),
],
('lorentz force', 'Hindi'): [
('Lorentz force combines electric and magnetic forces on a moving charge.', [1,2,3,4,5]),
('Magnetic force is zero when velocity is parallel to the field.', [12]),
('Magnetic force is maximal for velocity perpendicular to the field.', [13]),
('Magnetic force is perpendicular to both velocity and magnetic field.', [14]),
('Positive-charge magnetic-force direction follows the right-hand rule.', [15]),
('Negative charge reverses that force direction.', [16]),
('A magnetic field alone changes motion direction without changing speed.', [19]),
],
('optical isomerism', 'English'): [
('Optical isomerism is a form of stereoisomerism.', [1]),
('Optical isomers have the same molecular formula.', [1,11]),
('Optical isomers have the same connectivity.', [1,12]),
('Enantiomers are non-superimposable mirror-image molecular forms.', [1,2,14]),
('A carbon attached to four different groups is a chiral or asymmetric carbon.', [3,4,24]),
('A chiral center can give rise to two mirror-image forms.', [8]),
('Enantiomers share many physical properties.', [13]),
('Clockwise optical rotation is designated dextrorotatory or positive.', [17,27]),
('Anticlockwise optical rotation is designated levorotatory or negative.', [18,28]),
('Enantiomers rotate plane-polarized light equally in opposite directions.', [19]),
('Optical-rotation sign does not determine R/S configuration.', [20]),
('An equal mixture of enantiomers is racemic.', [21,22,29]),
('Equal opposing rotations cancel to give no net optical rotation.', [23]),
('Optical activity means the ability to rotate plane-polarized light.', [26]),
],
('optical isomerism', 'Hindi'): [
('Optical isomerism is a form of isomerism.', [1]),
('Optical isomers have the same molecular formula.', [2]),
('Optical isomers have the same connectivity.', [2]),
('Their different three-dimensional structures interact differently with polarized light.', [2]),
('A carbon attached to four different groups is a chiral center.', [3,4,17]),
('Enantiomers are non-superimposable mirror-image molecular forms.', [8,9,18]),
('Enantiomers rotate plane-polarized light equally in opposite directions.', [10]),
('Rightward rotation is designated positive.', [11,19]),
('Leftward rotation is designated negative.', [12,20]),
('An equal mixture of enantiomers is racemic.', [14,21]),
('Equal opposing rotations cancel to give zero net rotation.', [15]),
('Zero net optical rotation is called optical inactivity.', [16,22]),
],
('theory of relativity', 'English'): [
('Relativity has special and general theories.', [1,2,3]),
('Special relativity describes space and time for high-speed motion.', [2]),
('General relativity describes gravity through spacetime curvature.', [3,31]),
('Physical laws are identical for observers moving at constant velocity.', [5]),
('Vacuum light speed is invariant with respect to source and observer motion.', [6]),
('Moving clocks run slower relative to an observer: time dilation.', [8,9,10]),
('Motion contracts measured length along the motion direction.', [11,12,13]),
('Mass and energy are related, with mass interpretable as concentrated energy.', [14,15]),
('The large squared light speed means a small mass corresponds to large energy.', [16]),
('Newton describes gravity as an attractive force between objects.', [18]),
('Matter and energy curve spacetime.', [20,31]),
('Objects move through curved spacetime.', [20]),
('Physical spacetime is four-dimensional; the rubber sheet is only an analogy.', [23]),
('Clocks nearer a massive object run slower than clocks farther away.', [24,25]),
('GPS positioning requires relativistic corrections.', [26]),
('Relativity has invariant quantities, including the spacetime interval.', [32]),
],
('theory of relativity', 'Hindi'): [
('Relativity has special and general theories.', [2,3,4]),
('Physical laws are identical for uniformly moving observers.', [6]),
('Vacuum light speed is invariant with respect to observer motion.', [7,41]),
('Measured distances can depend on observer motion.', [8,40]),
('Elapsed time can depend on observer motion: time dilation.', [8,10,11,12,39]),
('The twin paradox is connected to motion-dependent elapsed time.', [13]),
('Mass and energy are related by E=mc2.', [14,42]),
('The large squared light speed means a small mass corresponds to large energy.', [16]),
('General relativity extends relativity to gravitation.', [17]),
('Newton describes gravity as a force between objects.', [18]),
('Mass and energy curve spacetime.', [20,29,43]),
('Objects move through curved spacetime.', [20]),
('The rubber-sheet analogy is a model, not the actual universe.', [25]),
('Spacetime has three spatial dimensions and one time dimension.', [26,27,28]),
('Stronger gravitation is associated with slower clock rates.', [32,33,39]),
('GPS positioning requires relativistic corrections to avoid accumulating errors.', [35]),
('Sufficient mass concentration can form a black hole through strong spacetime curvature.', [36,44]),
('The boundary of a black hole is called its event horizon.', [37]),
('Light cannot escape from inside the event horizon.', [38]),
]}

# Explicit mathematical relationships absent from the sentence-only extraction.
# These are additional only when the relationship is not already represented above.
FORMULA_CODES = {
('lorentz force','English'): [
('Electric force equals charge times electric field.', r'\vec F_E=q\vec E'),
('Magnetic-force magnitude depends on charge, speed, field and sine of their angle.', r'\boxed{F_B=qvB\sin\theta}'),
],
('lorentz force','Hindi'): [
('Electric force equals charge times electric field.', r'\vec F_E=q\vec E'),
('Magnetic-force magnitude depends on charge, speed, field and sine of their angle.', r'\boxed{F=qvB\sin\theta}'),
],
('crystal field theory','Hindi'): [
('Tetrahedral splitting is approximately four ninths of octahedral splitting.', r'\Delta_t \approx \frac{4}{9}\Delta_o'),
('The absorbed photon energy h nu equals the orbital energy gap.', r'\Delta = h\nu'),
],
}
