from __future__ import annotations

from tutoring_check.teachtune.config import SessionConfig

# A student can only speak to a knowledge component once its initial mastery reaches this level. Frozen for the whole session.
_CAN_SAY_THRESHOLD = 3


def can_say_components(config: SessionConfig) -> list[str]:
    """Knowledge components the student has the mastery to speak to."""
    return [
        name
        for name, mastery in config.knowledge_components.items()
        if mastery >= _CAN_SAY_THRESHOLD
    ]


def build_student_system_prompt(config: SessionConfig, trait_overview: str) -> str:
    """TeachTune Respond (Appendix A.5): the student's system prompt.

    `trait_overview` is the persona prose generated by the Interpret step (`generate_trait_overview`).

    String assembled once before the session loop and never rebuilt:
    `<can-say-only>` is fixed from the initial knowledge_components (the ones at or above the mastery threshold).
    `<profile>` holds the trait overview.
    Both XML blocks are always emitted so the structure is stable.
    """
    student = config.student_name
    can_say_block = "\n".join(f"You understand {name}." for name in can_say_components(config))

    return (
        f"You are {student}, a student learning about {config.topic} for the first time.\n"
        f"Forget all existing knowledge about {config.topic}.\n"
        f"Your conversation partner is {config.teacher_name}, a teacher.\n"
        'You only know the following. Answer questions beyond this content with "I don\'t know." or "I can\'t remember."\n'
        "Never answer questions that cannot be answered by combining the sentences below.\n"
        f"<{student}-can-say-only>\n"
        f"{can_say_block}\n"
        f"</{student}-can-say-only>\n"
        "You should behave as follows in the conversation.\n"
        f"<{student}-profile>\n"
        f"{trait_overview}\n"
        f"</{student}-profile>\n"
        "Answer in 2 lines or less. Answer clearly without detailed reasons or additional explanations.\n"
        f' Do not repeat "I don’t know" or "I can’t remember" and use various expressions, referring to <{student}-profile>.\n'
        f"Respond in {config.language}."
    )


def build_teacher_system_prompt(config: SessionConfig) -> str:
    """TeachTune teacher system prompt (Appendix A.2).

    Contains a teacher role, the topic + the elements the student must learn, then a fixed <instruction>. 
    """
    component_lines = "\n".join(f"- {name}" for name in config.knowledge_components)
    instruction = (
        "Teach only one element per message. "
        "Introduce a single idea in your own words, then stop and let the student respond before moving on. " # adapted for conversational tutoring context
        "Do not preview, list, or summarize the other elements. Bring them up only in later messages, one at a time."
    )
    return (
        "You are a teacher teaching students.\n"
        f"Your subject is {config.topic}, and the elements that students need to learn are as follows.\n"
        f"{component_lines}\n"
        "Follow the instructions below to teach a student. You must follow the contents of <instruction> exactly. "
        "Do not ask for additional questions if there is no direct mention.\n"
        "You are speaking out loud to the student, the way a tutor talks in conversation. "
        "Write 2-3 short spoken sentences. Never use numbered lists, bullet points, headings, " # adapted for conversational tutoring context
        'bold text, or any markdown. Do not label or count points ("1.", "First", etc.). '
        "Say one thing the way you would actually say it aloud.\n"
        "<instruction>\n"
        f"{instruction}\n"
        "</instruction>\n"
        f"Respond in {config.language}."
    )
